image: node:20

variables:
  CI: "true"

CI:
  interruptible: true
  # only:
  #   - main
  #   - merge_requests
  rules:
    - when: never
  script:
    - yarn install --frozen-lockfile
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
    - yarn nx affected --base=$NX_BASE --head=$NX_HEAD -t lint test build
