import { getAllProductionShows, getAllTeamPersons } from '@kedoo/shared/data-access';

import { ProductionPage } from '@kedoo/adults/feature-production';

export const metadata = {
  title: 'Our shows',
  // description: 'Generated by create-nx-workspace',
};

export default async function Production() {
  const shows = await getAllProductionShows();
  const persons = await getAllTeamPersons();

  return <ProductionPage shows={shows} persons={persons} />;
}
