import { AudiencePage } from '@kedoo/adults/feature-audience';

export const metadata = {
  title: 'Audience Management',
  // description: 'Generated by create-nx-workspace',
};

export default async function Audience() {
  return <AudiencePage />;
}
