import { ShowProfile } from '@kedoo/shared/utils-interfaces';

export const shows: ShowProfile[] = [
  {
    id: 1,
    name: 'The Wonder Guys',
    description:
      'Think you have seen it all? Think again. Join Steven Prior, director of Channel 4\'s "Hunted" and BBC\'s "Hidden Treasures of the National Trusts" and Emily Laing on “The Wonder Guys” as they shatter the postcard image of popular destinations and unveil the hidden worlds that simmer beneath the surface. Expect the unexpected. Notice the unnoticed.',
    episodes: '8',
    run_time: '60 mins',
    category: 'Series',
    genres: 'Adventure, Documentary, Travel',
    audience: 'All Gender, 18-44 Years Old',
    languages: 'English, Russian, Spanish',
    subtitles: '',
    release_date: '2024-Present',
    highlights_subs: '',
    highlights_others: 'Forecasting 150K views in first 30 days of episode premiere',
    director: 'Steven Prior',
    writer: '',
    stars: 'Steven Prior, Emily Laing',
    trailer: {
      ' WATCH NOW': {
        ' REQUEST A SCREENER': 'https://www.youtube.com/@thewonderguys/videos',
      },
    },
    imdb: '',
    images: 'https://drive.google.com/drive/folders/1m0pNgvyBi-obRq7LcDg9AHravkUybKvf?usp=sharing',
    awards: '',
  },
  {
    id: 2,
    name: 'Faraway',
    description:
      'Travel journalist Rada Samutti takes you beyond the stunning scenery, to embrace the vibrant culture, delicious food, and unique Traditions. Meet the locals, explore the beautiful landscapes and lose yourself in the music that defines a nation. “FARAWAY” is not just a TRAVEL DOCUSERIES. This is an experience.',
    episodes: '3',
    run_time: '60 mins',
    category: 'Series',
    genres: 'Documentary, Travel',
    audience: 'Female, 18-44 Years Old',
    languages: 'English, Russian, Spanish',
    subtitles: '',
    release_date: '2024-Present',
    highlights_subs: '',
    highlights_others: '6M+ views since its launch 6 months ago; 38% engagement rate',
    director: '',
    writer: '',
    stars: 'Rada Samutti',
    trailer: {
      ' WATCH NOW': {
        ' REQUEST A SCREENER': 'https://www.youtube.com/@prekrasnoetravel',
      },
    },
    imdb: '',
    images:
      'https://docs.google.com/presentation/d/1rV9Ll_TxX2PaQhUmrRkR07vZCcB4rOpmSn2Bs_dAMOc/edit?usp=sharing',
    awards: '',
  },
  {
    id: 3,
    name: 'Let’s Go',
    description:
      '"Let\'s Go" is a travel docuseries about how the world really works. Stas Natanzon, a journalist and traveler from Russia, takes us to all the offbeat and unusual places around the world. In everything scary, there is always something beautiful; in everything unknown, there is always something attractive.',
    episodes: '40',
    run_time: '60 mins',
    category: 'Series',
    genres: 'Adventure, Documentary, Travel',
    audience: 'Male, 18-44 Years Old',
    languages: 'Arabic, English, Portuguese, Russian, Spanish',
    subtitles: '',
    release_date: '2022-Present',
    highlights_subs: '2M',
    highlights_others: '40M views monthly; up to 2M views in first 30 days of episode premiere',
    director: 'Stas Natanzon',
    writer: '',
    stars: 'Stas Natanzon',
    trailer: {
      ' WATCH NOW': {
        ' REQUEST A SCREENER': 'https://www.youtube.com/@staspognali',
      },
    },
    imdb: '',
    images: 'https://drive.google.com/drive/folders/1mVfjhUv0tfX1-uS-vhVXaB-5SvCZ-PXj?usp=sharing',
    awards: '',
  },
  {
    id: 4,
    name: 'Podcast with Julia',
    description:
      'Julia Menshova, the iconic host of talk shows “I, Myself” in the 90s and “Alone with everyone” in the 2010s, is back for a steaming podcast. this time, she brews up conversation with celebrity guests as they share candid stories and heartfelt moments over a cup of coffee.',
    episodes: '100+ ',
    run_time: '60 mins',
    category: 'Series',
    genres: 'Reality, Talk Show',
    audience: '',
    languages: 'Russian',
    subtitles: '',
    release_date: '2020-Present',
    highlights_subs: '2.5M',
    highlights_others: '700M+ views in total',
    director: '',
    writer: '',
    stars: 'Julia Menshova',
    trailer: {
      ' WATCH NOW': {
        ' REQUEST A SCREENER': '',
      },
    },
    imdb: '',
    images: '',
    awards: '',
  },
  {
    id: 5,
    name: 'After Tomorrow',
    description:
      '“After Tomorrow” is a show that dives into the history and development of brands, gadgets and technologies we see and use everyday.  The host, Nikolay dubinin, is a tech enthusiast. He probes into how these innovations shape the past and change the future. Get ready for an insight analysis from him!',
    episodes: '67',
    run_time: '30 mins',
    category: 'Series',
    genres: 'Documentary, Science',
    audience: '',
    languages: 'Russian',
    subtitles: '',
    release_date: '2021-Present',
    highlights_subs: '1.6M',
    highlights_others: '760M+ views in total',
    director: 'Nikolay Dubinin',
    writer: '',
    stars: 'Nikolay Dubinin',
    trailer: {
      ' WATCH NOW': {
        ' REQUEST A SCREENER': 'https://www.youtube.com/channel/UC9Rc75wIi4wh5Ir4Th8Di_g',
      },
    },
    imdb: '',
    images: '',
    awards: '',
  },
  {
    id: 6,
    name: 'Startup B.C.',
    description:
      '“Startup BC” Is an Animated sitcom that tells the story of 5 friends in the prehistoric world: ingenious inventor Khabi; handsome designer Kroma; strongman with a gentle soul Tumm; rebel Aname and mysterious stranger Ori, as they struggle to start up a sneaker business in a world where everyone is walking barefoot.',
    episodes: '12',
    run_time: '22 mins',
    category: 'Series',
    genres: 'Animation, Comedy, Teen',
    audience: 'All Gender, 18-34 Years Old',
    languages: 'English, Russian',
    subtitles: '',
    release_date: '2025-2026',
    highlights_subs: '',
    highlights_others: '',
    director: 'TBC',
    writer: 'TBC',
    stars: 'TBC',
    trailer: {
      ' WATCH NOW': {
        ' REQUEST A SCREENER': '',
      },
    },
    imdb: '',
    images: 'https://drive.google.com/file/d/1OOeeoOxrCbhAiPGjgCbjqu2_ZfYAkKX8/view?usp=drive_link',
    awards: '',
  },
  {
    id: 7,
    name: 'Conviction ',
    description:
      'From the creators of “The Black Yard”, set within a serene town in 2009, a schoolboy named Aktan with ambitions of entering the National Security Committee confronts the blatant injustice within the local judicial system.',
    episodes: 'Featured Length',
    run_time: '97 mins',
    category: 'Films',
    genres: 'Crime, Drama, Thriller',
    audience: 'All Gender, 18-34 Years Old',
    languages: 'Russian',
    subtitles: 'English',
    release_date: '2024',
    highlights_subs: '',
    highlights_others:
      'From the Creators of hit series & BIFF Best Asian TV Series nominee "A Dark Yard"',
    director: 'Dias Bertis',
    writer: 'Dias Bertis, Alen Rakhemtaliyev',
    stars: 'Rauan Akhmedov, Damir Amangeldin, Aibar Saly',
    trailer: {
      ' WATCH NOW': {
        ' REQUEST A SCREENER':
          'https://drive.google.com/file/d/1E5ja38pmobvUVEG_Ww3vrQdlGkwIKBrm/view?usp=sharing',
      },
    },
    imdb: 'https://www.imdb.com/title/tt31775030/',
    images: 'https://drive.google.com/file/d/18JcoNhhP8sgGiUpWpOzQaKA2h9DnBvu1/view?usp=sharing',
    awards: '',
  },
];
