import {
  getAllChannels,
  getAllProductionShows,
  getAllTeamPersons,
  getKidsPartners,
} from '@kedoo/shared/data-access';

import { DistributionPage } from '@kedoo/adults/feature-distribution';

export const metadata = {
  title: 'Our catalogue',
  // description: 'Generated by create-nx-workspace',
};

export default async function Distribution() {
  const shows = await getAllProductionShows();
  const persons = await getAllTeamPersons();
  const partners = await getKidsPartners();
  const channels = await getAllChannels();

  return (
    <DistributionPage shows={shows} persons={persons} partners={partners} channels={channels} />
  );
}
