import { ShowKidsProfile } from '@kedoo/shared/utils-interfaces';

export const shows: ShowKidsProfile[] = [
  {
    id: 'booba',
    name: 'Booba',
    description:
      'A funky and curious little creature who  missed 200 years of human evolution. Join him and his friends as they explore the world, encountering awkward situations, yet always managing to save the day together.',
    episodes: '5 Seasons',
    run_time: "26 x 4-7'",
    category: 'Series',
    genres: 'Entertainment',
    audience: 'Pre-school / Family',
    languages: 'Non-dialogue',
    subtitles: '',
    release_date: '2014',
    highlights_subs: '',
    highlights_others: 'Half hours also available',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://www.youtube.com/@Booba',
    },
    imdb: 'https://www.imdb.com/title/tt6581428/?ref_=fn_al_tt_1',
    images: [1, 2, 3, 4, 5, 6, 7],
    awards: '',
  },
  {
    id: 'booba_food_puzzle',
    name: 'Booba: Food Puzzle',
    description:
      "A fun-filled cooking adventure with Booba, now a chef and co-host of an exciting show! Cook alongside Booba and his pals Loola, Noodle, and Spike as they guide you through making delicious meals. Expect lots of laughter, surprises, and culinary creativity. Best of all, you get to enjoy the tasty treats you've made together!",
    episodes: 'Season 1',
    run_time: "26 x 3'",
    category: 'Series',
    genres: 'Educational',
    audience: 'Pre-school / Family',
    languages: 'Non-dialogue',
    subtitles: '',
    release_date: '2020',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://www.youtube.com/playlist?list=PL9F-fmslIdEvpKIZdJ0Zc9BaK5_4nMDSb',
    },
    imdb: '',
    images: [1, 2, 3, 4, 5, 6],
    awards: '',
  },
  {
    id: 'booba_bedtime_stories',
    name: "Booba's Bedtime Stories",
    description:
      'Listen to the captivating bedtime stories about Booba and his friends! You can enjoy tales of their endless adventures which are always full of joy. Each story brings laughter and shares heartwarming moments, leaving you excited for the next one. Booba says that sweet dreams are just a story away!',
    episodes: 'Season 1',
    run_time: "10 x 10-13'",
    category: 'Series',
    genres: 'Entertainment',
    audience: 'Pre-school / Family',
    languages: 'English',
    subtitles: '',
    release_date: '2023',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://youtube.com/playlist?list=PLJHAODBevOR-8K72xpNzQ06g8sdKYbh5Y&feature=shared',
    },
    imdb: '',
    images: [1, 2, 3, 4, 5, 6, 7, 8],
    awards: '',
  },
  {
    id: 'sonya_from_toastville',
    name: 'Sonya from Toastville',
    description:
      "One day, Sonya stumbles upon a remarkable secret hidden within her kitchen: a bread box with magical powers. By placing a toast magnet and giving it a twist, she's teleported away from the human world to the quirky town of Toastville, located on the colorful planet of Toastland.",
    episodes: 'Season 1',
    run_time: "26 x 11'",
    category: 'Series',
    genres: 'Adventure',
    audience: 'Ages 6-9',
    languages: 'English, Spanish, Portuguese',
    subtitles: '',
    release_date: '2024',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://www.youtube.com/@SonyaFromToastville_INT',
    },
    imdb: '',
    images: [1, 2, 3, 4, 5, 6, 7],
    awards: '',
  },
  {
    id: 'leo_and_tig',
    name: 'Leo and Tig',
    description:
      'Join Leo & Tig, two cubs of different species. Tig is thoughtful and genuine, while Leo is a lighthearted explorer, always curious about life. Together, they uncover the world’s beauties, dangers, and legends full of excitement and surprises.',
    episodes: '2 Seasons',
    run_time: "26 x 11'",
    category: 'Series',
    genres: 'Adventure',
    audience: 'Ages 6+',
    languages: 'English, French',
    subtitles: '',
    release_date: '2016',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: { data: 'https://www.youtube.com/@leoandtig/featured' },
    imdb: 'https://www.imdb.com/title/tt7358910/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Leo%2520and%2520Tig',
    images: [1, 2, 3],
    awards: '',
  },
  {
    id: 'be_be_bears',
    name: 'Be-Be-Bears',
    description:
      'North and south, winter and summer, adventures and education, Bucky and Bjorn. Two of these friends will take kids to the world of amazing discoveries, beautiful nature and true friendship.',
    episodes: '4 Seasons',
    run_time: '26 x 5\'30"',
    category: 'Series',
    genres: 'Adventure',
    audience: 'Ages 3-7',
    languages: 'English, Spanish, French, German',
    subtitles: '',
    release_date: '2015',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: { data: 'https://www.youtube.com/@bebebears' },
    imdb: 'https://www.imdb.com/title/tt7037778/?ref_=fn_al_tt_1',
    images: [1, 2, 3, 4, 5, 6],
    awards: '',
  },
  {
    id: 'fantasy_patrol',
    name: 'Fantasy Patrol ',
    description:
      'Fantasy Patrol crew - Cat the Scientist, Magic Flower, Elizabeth Wise, Wood-Sprite. Each story follows the adventures and reveal their super power. Kids will learn about previously hidden secrets and the past.',
    episodes: 'Season 1',
    run_time: "26 x 11'",
    category: 'Series',
    genres: 'Entertainment',
    audience: 'Girls 6+',
    languages: 'English, Spanish',
    subtitles: '',
    release_date: '2016',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: { data: 'https://www.youtube.com/@fantasypatrol' },
    imdb: 'https://www.imdb.com/title/tt8091356/?ref_=fn_al_tt_1',
    images: [1, 2, 3, 4],
    awards: '',
  },
  {
    id: 'magic_lantern',
    name: 'Magic Lantern',
    description:
      "Every day Kate with her brother Micky watches different stories from books of classical literature: Jules Verne, Edgar Poe, Lewis Carroll and many others on their film-strip. Each episode has its own style and broadens kids' minds.",
    episodes: '3 Seasons',
    run_time: '26 x 5\'30"',
    category: 'Series',
    genres: 'Edutainment',
    audience: 'Ages 6+',
    languages: 'English, Spanish',
    subtitles: '',
    release_date: '2017',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://youtube.com/playlist?list=PLLdP66hNN3orOX3ClQBipm9Dq1iXd3Vh4&feature=shared',
    },
    imdb: '',
    images: [1, 2, 3, 4, 5, 6, 7],
    awards: '',
  },
  {
    id: 'cutie_cubies',
    name: 'Cutie Cubies',
    description:
      'A colorful and immersive series for preschoolers follows four small cubic aliens embarking on adventures to explore other worlds. Traveling through the entire solar system, they land on a small planet where one transforms into grass, another into an aquarium with a fish, yet each retains their originality and boundless curiosity.',
    episodes: 'Season 1',
    run_time: "26 x 11''",
    category: 'Series',
    genres: 'Adventure',
    audience: 'Preschool',
    languages: 'English, Spanish',
    subtitles: '',
    release_date: '2017',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://youtube.com/playlist?list=PLLdP66hNN3or9aw1htE86tMh_p8Ihsgwc&feature=shared',
    },
    imdb: '',
    images: [1, 2, 3, 4, 5, 6, 7],
    awards: '',
  },
  {
    id: 'heroes_of_envell',
    name: 'Heroes of Envell',
    description:
      'Four schoolmates find an unusual laptop, a portal to the world of the game "Heroes of Envell" with real adventures and real dangers. The quest may turn into a race, shooting competition. But one thing is clear - it certainly won\'t be boring.',
    episodes: '2 Seasons',
    run_time: "26 x 11'",
    category: 'Series',
    genres: 'Adventure',
    audience: 'Boys 6+',
    languages: 'English, Spanish',
    subtitles: '',
    release_date: '2017',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://youtube.com/playlist?list=PLLdP66hNN3orv_ScxqBUFNiobqLVI97ZM&feature=shared',
    },
    imdb: 'https://www.imdb.com/title/tt13535142/?ref_=fn_al_tt_1',
    images: [1, 2, 3, 4, 5],
    awards: '',
  },
  {
    id: 'woodventures',
    name: 'Woodventures',
    description:
      'A musical animated series for preschoolers featuring wooden toys living in a small wooden town. Each toy has a unique personality and reacts differently to various life events. Together with the audience, the toys face challenges, solve problems, and learn about friendship, all while never stopping their play and fun.',
    episodes: '2 Seasons',
    run_time: '26 x 5\'30"',
    category: 'Series',
    genres: 'Music, Education',
    audience: 'Preschool',
    languages: 'English, Spanish',
    subtitles: '',
    release_date: '2017',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://www.youtube.com/@woodventures',
    },
    imdb: '',
    images: [1, 2, 3, 4, 5, 6, 7],
    awards: '',
  },
];
