import { ShowKidsProfile } from '@kedoo/shared/utils-interfaces';

export const shows: ShowKidsProfile[] = [
  {
    id: 'dragons',
    name: 'Dragons',
    description: '',
    episodes: 'Featured Length',
    run_time: '90 mins',
    category: 'Films',
    genres: '',
    audience: '',
    languages: '',
    subtitles: '',
    release_date: '',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {},
    imdb: '',
    images: [1],
    awards: '',
  },
  {
    id: 'booba',
    name: 'Booba',
    description:
      'A funky and curious little creature who  missed 200 years of human evolution. Join him and his friends as they explore the world, encountering awkward situations, yet always managing to save the day together.',
    episodes: '5 Seasons',
    run_time: "26 x 4-7'",
    category: 'Series',
    genres: 'Entertainment',
    audience: 'Pre-school / Family',
    languages: 'Non-dialogue',
    subtitles: '',
    release_date: '2014',
    highlights_subs: '',
    highlights_others: 'Half hours also available',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://www.youtube.com/@Booba',
    },
    imdb: 'https://www.imdb.com/title/tt6581428/',
    images: [1, 2, 3, 4, 5, 6, 7],
    awards: '',
  },
  {
    id: 'booba_food_puzzle',
    name: 'Booba: Food Puzzle',
    description:
      "A fun-filled cooking adventure with Booba, now a chef and co-host of an exciting show! Cook alongside Booba and his pals Loola, Noodle, and Spike as they guide you through making delicious meals. Expect lots of laughter, surprises, and culinary creativity. Best of all, you get to enjoy the tasty treats you've made together!",
    episodes: 'Season 1',
    run_time: "26 x 3'",
    category: 'Series',
    genres: 'Educational',
    audience: 'Pre-school / Family',
    languages: 'Non-dialogue',
    subtitles: '',
    release_date: '2020',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://www.youtube.com/playlist?list=PL9F-fmslIdEvpKIZdJ0Zc9BaK5_4nMDSb',
    },
    imdb: 'https://www.imdb.com/title/tt12319946/',
    images: [1, 2, 3, 4, 5, 6],
    awards: '',
  },
  {
    id: 'booba_bedtime_stories',
    name: "Booba's Bedtime Stories",
    description:
      'Listen to the captivating bedtime stories about Booba and his friends! You can enjoy tales of their endless adventures which are always full of joy. Each story brings laughter and shares heartwarming moments, leaving you excited for the next one. Booba says that sweet dreams are just a story away!',
    episodes: 'Season 1',
    run_time: "10 x 10-13'",
    category: 'Series',
    genres: 'Entertainment',
    audience: 'Pre-school / Family',
    languages: 'English',
    subtitles: '',
    release_date: '2023',
    highlights_subs: '',
    highlights_others: '',
    director: '',
    writer: '',
    stars: '',
    trailer: {
      data: 'https://youtube.com/playlist?list=PLJHAODBevOR-8K72xpNzQ06g8sdKYbh5Y&feature=shared',
    },
    imdb: '',
    images: [1, 2, 3, 4, 5, 6, 7, 8],
    awards: '',
  },
  {
    id: 'sonya_from_toastville',
    name: 'Sonya from Toastville',
    description:
      "One day, Sonya stumbles upon a remarkable secret hidden within her kitchen: a bread box with magical powers. By placing a toast magnet and giving it a twist, she's teleported away from the human world to the quirky town of Toastville, located on the colorful planet of Toastland.",
    episodes: 'Season 1',
    run_time: "26 x 11'",
    category: 'Series',
    genres: 'Adventure',
    audience: 'Ages 6-9',
    languages: 'Arabic, English, Spanish, Portuguese, Russian',
    subtitles: '',
    release_date: '2024',
    highlights_subs: '',
    highlights_others: '',
    director: 'Dmitriy Vysotskiy',
    writer: 'Aron Dunn, Dmitriy Vysotskiy',
    stars: 'Jamie Carr, Liana Bdewi, Patrick Speagle',
    trailer: { data: 'https://www.youtube.com/@SonyaFromToastville_INT' },
    imdb: 'https://www.imdb.com/title/tt32090505/',
    images: [1, 2, 3, 4, 5, 6, 7],
    awards: '',
  },
];
