import { MainPage } from '@kedoo/kids/feature-main';

export const metadata = {
  title: 'Kids',
  // description: 'Generated by create-nx-workspace',
};

export default function KidsMain() {
  return <MainPage />;
}
