import { ContactsPage } from '@kedoo/adults/feature-contacts';

export const metadata = {
  title: 'Contacts',
  // description: 'Generated by create-nx-workspace',
};

export default function Contacts() {
  return <ContactsPage />;
}
